# version: '3.9'

# services:
#   php:
#     build: .
#     volumes:
#      - ./src:/var/www/html
#     ports:
#      - '8000:8000'
#   mysql:
#     platform: linux/x86_64 #M1Macはこれを追加しないと動かない
#     image: mysql:5.7
#     ports:
#       - '3306:3306'
#     volumes:
#       - ./db:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: laravel
version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data

  # 追記
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data